project:
  type: website

website:
  title: "Drive Rojrachsombat's Home Page"
  navbar:
    left:
      - text: "About"
        href: about.html
      - text: "Rayshader Blog"
        href: Rayshader-Blog.html
      - text: "Favorite Links"
        href: favorite-links.html
    tools:
      - icon: github
        href: https://github.com/drivetera
      - icon: email
        href: mailto:terachet@stanford.edu

format:
  html:
    css: styles.css
    toc: true
    theme:
      - default
brand: _brand.yml

footer: |
    <footer>
      <p>© 2024 Stanford University. All Rights Reserved.</p>
      <img src="assets/block-s.png" alt="Stanford Logo" class="stanford-logo">
    </footer>
